version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: news_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: news_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    build: .
    container_name: news_api
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: root:password@tcp(mysql:3306)/news_db?charset=utf8mb4&parseTime=True&loc=Local
      JWT_SECRET: i1cDUBFwjiz8prLcz4ClTS6jMpT14omp
      PORT: :8080
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: